exclude_paths:
  - '**/build/**' # Exclude build directories
  - '**/coverage/**' # Exclude coverage directories
  - '**/dist/**' # Exclude distribution directories
  - '**/docs/**' # Exclude documentation directories
  - '**/e2e/**' # Exclude end-to-end test directories
  - '**/log/**' # Exclude log directories
  - '**/logs/**' # Exclude logs directories
  - '**/node_modules/**' # Exclude node_modules directories
  - '**/spec/**' # Exclude spec directories
  - '**/test/**' # Exclude test directories (singular)
  - '**/tests/**' # Exclude tests directories (plural)
  - '**/tmp/**' # Exclude temporary directories
  - '**/vendor/**'
  - '**.md'
  - '**.min.css'
  - '**.min.js'
